[End-to-End Fraud Detection Demo] Fix for a DataWrangler template
Template is missing "seed" attribute which cause a error in DataWrangles flow.

Error text:
ComputeValueError: Incorrect sampling configurations for sampling method sample_by_ratio;Expected: ['sample_ratio', 'seed'], received: {'sample_ratio': 1}