Remove deprecated method call as_matrix
There was the following error AttributeError: 'DataFrame' object has no attribute 'as_matrix'
The 'as_matrix' method is deprecated since pandas version 0.23.0. Reportedly, a new method 'to_numpy' should be used now in the spirit of better consistency throughout the API.